#!/bin/bash
source ./pref.cfg

function maximize () {
if [ -e "$ecdir/maximized" ]
  then
    clear
  else 
    sleep 2
    wmctrl -F -r PMHT -b toggle,fullscreen
    touch $ecdir/maximized
fi
}



#tty > tty.info
#if [ -z $DISPLAY ]
#  then
#    DIALOG=dialog
#  else
#    DIALOG=Xdialog
#  fi

function checkpassword () {
oldpass=$(cat $menu/password)
if [ "$oldpass" != "" ]
then 
  dialog --passwordbox  " To proceed you must enter the password... " 8 50 2>$tmp/pmht_tmp.$$
  newpass=$(cat $tmp/pmht_tmp.$$)
  if [ "$oldpass" != "$newpass" ]
  then
    dialog --msgbox "Wrong Password!!!" 5 30
    rm -f $tmp/pmht_tmp.$$
    exec $ecdir/emucom
  fi
fi
}

maximize

dialog --backtitle "Poor Mans Home Theater" \
--no-cancel --no-tags --menu "Main Menu" 22 40 15 \
1 "Console Emulators" \
2 "News" \
10 "Weather" \
3 "Movies" \
8 "Online TV" \
9 "Online Radio" \
4 "Music" \
5 "Youtube" \
6 "Poor Mans Spotify (PMS)" \
7 "Restricted" \
C "Activate Screensaver" \
S Settings \
H "Help" \
X Exit 2> $tmp/answer

if [ "$?" = "0" ]
then
	ch=$(cat $tmp/answer)
	case $ch in
	# /home is selected
	  1) exec $menu/emulators.sh;;
          2) exec $menu/rss.sh;;
	  3) exec $menu/movies.sh;;
	  4) exec $menu/music.sh;;
	  5) mpsyt
	     exec $ecdir/emucom;;
	  6) mps
	     exec $ecdir/emucom;;
	  7) checkpassword
	     exec $menu/restricted.sh;;
	  8) exec $menu/otv.sh;;
          9) exec $menu/oradio.sh;;
	  10) exec $menu/weather.sh;;
 	  C) cmatrix -s -b -C $(cat $ecdir/theme)
	     exec $ecdir/emucom;;
	  S) exec $menu/settings.sh;;
	  H) exec $menu/help.sh;;
	  X) exec $menu/exit.sh;;
	  *) exec $ecdir/emucom;;
        esac
 
# Cancel is pressed
else
        exec $ecdir/emucom
fi
exit
